language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - composer global require hirak/prestissimo
  - composer update $PREFER_LOWEST

script:
  - composer validate --no-check-all --strict
  - composer require --dev php-coveralls/php-coveralls:~2 codacy/coverage:~1
  - mkdir -p build/logs
  - vendor/bin/phpunit --testsuite=unit --coverage-text  --coverage-clover build/logs/clover.xml
  - php tests/systemTests.php

after_script:
  - vendor/bin/coveralls -v
  - vendor/bin/codacycoverage clover build/logs/clover.xml
